site_name: pygismeteo
repo_url: https://github.com/monosans/pygismeteo
repo_name: monosans/pygismeteo
edit_uri: edit/main/docs/
nav:
  - index.md
  - install.md
  - gismeteo.md
  - current.md
  - step3.md
  - step6.md
  - step24.md
  - search.md
  - session.md
  - types.md
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.top
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/droplet
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Тёмный режим
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Светлый режим
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/monosans
      name: Telegram разработчика
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/monosans
      name: LinkedIn разработчика
markdown_extensions:
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - minify_html
